function run(Event_list, max_time, log_file)

% global node mac_status;
global current_time;

% Event driven simulation loop
while 1
    [min_instant, min_index] = min([Event_list(:).instant]);
    if isempty(min_instant)
        break;
    end
    if min_instant > max_time
        break;
    end
    NewEvents = Simulation_IDDR(Event_list(min_index), log_file);      % Get new events from executing the latest 'action'
    current_time = min_instant;
    Event_list(min_index) = [];                     % Delete the latest event which has been just executed.
    Event_list = [NewEvents; Event_list];   % Append new events generated by executing the latest event
end

return;